// Auto-generated by build-bundle.mjs. Do not edit by hand.

export interface LogicFlowModel {
  id: string;
  label?: string;
  modelType?: string;
  contentType?: string;
  expressionLanguage?: string;
  logicFlow: {
    variables: { input?: unknown[]; output?: unknown[] };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}

export interface RuntimeLogger {
  log(severity: number, message: string, ...vars: unknown[]): void;
}

export interface RuntimeResponse {
  runId: string;
  outputData: Record<string, unknown>;
  traceData: { trace: unknown[]; totalDuration: number };
  errorOutput: RunOutputError[];
  runtimeErrors: RunOutputError[];
}

/**
 * A message a blueprint produced. The type and fields describe a typed throw
 * (ENG-2693) and are absent on a runtime fault.
 */
export interface RunOutputError {
  title: string;
  detail: string;
  type?: string;
  fields?: Record<string, unknown>;
}

export interface Manifest {
  project: { id: string; label: string };
  blueprints: Array<{
    slug: string;
    modelId: string;
    label: string;
    jsonPath?: string;
    helpers?: Array<{ modelId: string; label: string; jsonPath: string }>;
  }>;
  /** Project type model, when the project declares types. */
  types?: { modelId: string; label: string; jsonPath: string };
}

export interface TypeModel {
  id: string;
  label: string;
  description?: string;
  modelType?: string;
  types: unknown[];
  [k: string]: unknown;
}

export interface Project {
  manifest: Manifest;
  models: Record<string, LogicFlowModel>;
  helpers?: LogicFlowModel[];
  /**
   * Parsed `types.json` (the file `manifest.types.jsonPath` points at).
   * With it, `date` outputs declared through a named alias or nested in a
   * structure come back as `YYYY-MM-DD`.
   */
  typeModel?: TypeModel | null;
}

export interface RunBlueprintOptions {
  logger?: RuntimeLogger;
}

export function runBlueprint(
  project: Project,
  blueprintSlug: string,
  input: Record<string, unknown>,
  options?: RunBlueprintOptions,
): Promise<RuntimeResponse>;

export interface BlueprintDescription {
  input: Record<string, unknown>;
  output: Record<string, unknown>;
}

export function describeBlueprint(
  project: Project,
  blueprintSlug: string,
): BlueprintDescription;
