// Auto-generated by build-bundle.mjs. Do not edit by hand.

export interface LogicFlowModel {
  id: string;
  label?: string;
  modelType?: string;
  contentType?: string;
  expressionLanguage?: string;
  logicFlow: {
    variables: { input?: unknown[]; output?: unknown[] };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}

export interface RuntimeLogger {
  log(severity: number, message: string, ...vars: unknown[]): void;
}

export interface RuntimeResponse {
  runId: string;
  outputData: Record<string, unknown>;
  traceData: { trace: unknown[]; totalDuration: number };
  errorOutput: Array<{ title: string; detail: string }>;
  runtimeErrors: Array<{ title: string; detail: string }>;
}

export type BlueprintLibrary =
  | Record<string, LogicFlowModel>
  | Map<string, LogicFlowModel>;

export interface RunBlueprintOptions {
  library?: BlueprintLibrary;
  appId?: string;
  logger?: RuntimeLogger;
}

export function runBlueprint(
  model: LogicFlowModel,
  input: Record<string, unknown>,
  options?: RunBlueprintOptions,
): Promise<RuntimeResponse>;

export interface BlueprintDescription {
  input: Record<string, unknown>;
  output: Record<string, unknown>;
}

export function describeBlueprint(model: LogicFlowModel): BlueprintDescription;

export function initializeQuickJS(): Promise<void>;

export class MapBasedBlueprintResolver {
  constructor(blueprints: BlueprintLibrary);
}

export class LogicRuntime {
  static readonly BROWSER_DEFAULTS: unknown;
  static readonly SERVER_DEFAULTS: unknown;
  constructor(options?: unknown, resolver?: unknown, logger?: RuntimeLogger);
  execute(model: LogicFlowModel, input: Record<string, unknown>, appId?: string): RuntimeResponse;
}
